#!/usr/bin/env python
from __future__ import annotations

import argparse
import os
import pprint
import random
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from agents import MolecularAgent, ProteinAgent


@dataclass
class DatasetContext:
    dataset_name: str


def parse_numbered_items(text: str) -> list[str]:
    items: list[str] = []
    for line in text.splitlines():
        cleaned = line.strip()
        if not cleaned:
            continue
        cleaned = re.sub(r"^\s*(?:\d+[\).:-]\s*|-+\s*)", "", cleaned).strip()
        cleaned = cleaned.strip("`'\" ")
        if cleaned:
            items.append(cleaned)
    return list(dict.fromkeys(items))


def sample_records(train: pd.DataFrame, sample_size: int, seed: int) -> list[dict[str, Any]]:
    required = [column for column in ["drug", "target", "label"] if column in train.columns]
    if not required:
        raise ValueError("Training data must contain at least one of drug, target, label columns.")

    rng = random.Random(seed)
    indices = list(train.index)
    selected = rng.sample(indices, min(sample_size, len(indices)))
    return train.loc[selected, required].to_dict("records")


def load_existing_keys(path: str | None) -> tuple[list[str], list[str]]:
    if not path:
        return [], []

    from downstream_ml.validation import load_feature_vocab

    substructures, fragments = load_feature_vocab(path)
    return list(substructures.keys()), list(fragments.keys())


def write_vocab(path: Path, substructures: list[str], fragments: list[str]) -> None:
    substructure_patterns = {item: {"count": 1, "smile": [item]} for item in substructures}
    binding_fragments = {item: {"count": 1} for item in fragments}

    body = [
        "# Generated by scripts/mine_knowmol_features.py",
        "substructure_patterns = " + pprint.pformat(substructure_patterns, sort_dicts=False, width=120),
        "",
        "binding_fragments = " + pprint.pformat(binding_fragments, sort_dicts=False, width=120),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(body))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Mine KnowMol molecular SMARTS and protein fragments with LLM agents."
    )
    parser.add_argument("--dataset", choices=["davis", "drugbank", "kiba", "bace", "bbbp", "freesolv"], required=True)
    parser.add_argument("--data", required=True, help="CSV file or split directory containing train/valid/test CSVs")
    parser.add_argument("--output", required=True, help="Output Python file with substructure_patterns and binding_fragments")
    parser.add_argument("--existing-vocab", help="Optional Python vocab file whose keys should be excluded")
    parser.add_argument("--mode", choices=["both", "molecule", "protein"], default="both")
    parser.add_argument("--sample-size", type=int, default=20)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--model", default=os.environ.get("KNOWMOL_AGENT_MODEL", "pro-deepseek-r1"))
    parser.add_argument("--api-key", default=os.environ.get("OPENAI_API_KEY"))
    parser.add_argument("--api-base", default=os.environ.get("OPENAI_BASE_URL"))
    return parser


def main() -> None:
    args = build_parser().parse_args()
    from downstream_ml.validation import read_or_split_dataset

    train, _, _ = read_or_split_dataset(args.data, args.dataset, args.seed)
    samples = sample_records(train, args.sample_size, args.seed)
    existing_substructures, existing_fragments = load_existing_keys(args.existing_vocab)
    context = DatasetContext(dataset_name=args.dataset)

    substructures: list[str] = []
    fragments: list[str] = []

    if args.mode in {"both", "molecule"}:
        molecular_agent = MolecularAgent(
            name="MolecularAgent",
            dataset=context,
            model=args.model,
            api_key=args.api_key,
            api_base=args.api_base,
        )
        molecular_text = molecular_agent.generate_substructure(samples, existing_substructures)
        substructures = parse_numbered_items(molecular_text)
        print(f"Molecular substructures: {len(substructures)}")

    if args.mode in {"both", "protein"}:
        protein_agent = ProteinAgent(
            name="ProteinAgent",
            dataset=context,
            model=args.model,
            api_key=args.api_key,
            api_base=args.api_base,
        )
        protein_text = protein_agent.generate_substructure(samples)
        fragments = [item for item in parse_numbered_items(protein_text) if item not in existing_fragments]
        print(f"Protein fragments: {len(fragments)}")

    write_vocab(Path(args.output).expanduser(), substructures, fragments)
    print(f"Saved KnowMol feature vocabulary: {args.output}")


if __name__ == "__main__":
    main()
