from __future__ import annotations

import copy
import pprint
import re
from pathlib import Path
from typing import Any

from rdkit import Chem


class FeatureAggregator:
    """Aggregate discovered drug SMARTS and target fragments into a feature vocabulary."""

    def __init__(self, substructures: dict[str, Any] | None = None, fragments: dict[str, Any] | None = None) -> None:
        self.substructures: dict[str, dict[str, Any]] = dict(substructures or {})
        self.fragments: dict[str, dict[str, Any]] = dict(fragments or {})
        self.last_drug_keys: list[str] = []
        self.last_target_keys: list[str] = []

    def clone(self) -> "FeatureAggregator":
        return FeatureAggregator(copy.deepcopy(self.substructures), copy.deepcopy(self.fragments))

    def _parse_numbered_items(self, text: str) -> list[str]:
        items: list[str] = []
        for line in text.splitlines():
            cleaned = line.strip()
            if not cleaned:
                continue
            cleaned = re.sub(r"^\s*(?:\d+[\).:-]\s*|-+\s*)", "", cleaned).strip()
            cleaned = cleaned.strip("`'\" ")
            if cleaned:
                items.append(cleaned)
        return items

    def add_drug_features(self, text: str) -> int:
        added = 0
        touched_keys: list[str] = []
        for smarts in self._parse_numbered_items(text):
            mol = Chem.MolFromSmarts(smarts)
            if mol is None:
                continue
            canonical = Chem.MolToSmarts(mol)
            touched_keys.append(canonical)
            if canonical in self.substructures:
                self.substructures[canonical]["count"] = self.substructures[canonical].get("count", 0) + 1
                if smarts not in self.substructures[canonical].setdefault("smile", []):
                    self.substructures[canonical]["smile"].append(smarts)
            else:
                self.substructures[canonical] = {"count": 1, "smile": [smarts]}
                added += 1
        self.last_drug_keys = list(dict.fromkeys(touched_keys))
        return added

    def add_target_features(self, text: str) -> int:
        added = 0
        touched_keys: list[str] = []
        for fragment in self._parse_numbered_items(text):
            normalized = re.sub(r"[^A-Za-z]", "", fragment).upper()
            if not normalized:
                continue
            touched_keys.append(normalized)
            if normalized in self.fragments:
                self.fragments[normalized]["count"] = self.fragments[normalized].get("count", 0) + 1
            else:
                self.fragments[normalized] = {"count": 1}
                added += 1
        self.last_target_keys = list(dict.fromkeys(touched_keys))
        return added

    def consolidate_from(
        self,
        candidate: "FeatureAggregator",
        drug_keys: list[str],
        target_keys: list[str],
        validation_gain: float,
    ) -> None:
        for key in drug_keys:
            if key not in candidate.substructures:
                continue
            entry = copy.deepcopy(candidate.substructures[key])
            self._update_memory_value(entry, validation_gain)
            self.substructures[key] = entry

        for key in target_keys:
            if key not in candidate.fragments:
                continue
            entry = copy.deepcopy(candidate.fragments[key])
            self._update_memory_value(entry, validation_gain)
            self.fragments[key] = entry

    def _update_memory_value(self, entry: dict[str, Any], validation_gain: float) -> None:
        entry["alpha"] = max(float(entry.get("alpha", 0.0)), float(validation_gain))
        gamma = dict(entry.get("gamma", {}))
        gamma["recurrence"] = int(gamma.get("recurrence", 0)) + 1
        gamma["cumulative_validation_gain"] = float(gamma.get("cumulative_validation_gain", 0.0)) + float(validation_gain)
        entry["gamma"] = gamma

    def write_vocab(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        body = [
            "# Generated by KnowMol FeatureAggregator",
            "substructure_patterns = "
            + pprint.pformat(self.substructures, sort_dicts=False, width=120),
            "",
            "binding_fragments = " + pprint.pformat(self.fragments, sort_dicts=False, width=120),
            "",
        ]
        path.write_text("\n".join(body))

    def write_drug_dict(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "substructure_patterns = "
            + pprint.pformat(self.substructures, sort_dicts=False, width=120)
            + "\n"
        )

    def write_protein_dict(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "binding_fragments = "
            + pprint.pformat(self.fragments, sort_dicts=False, width=120)
            + "\n"
        )

    def write_dicts(self, drug_path: Path, protein_path: Path) -> None:
        self.write_drug_dict(drug_path)
        self.write_protein_dict(protein_path)

    def write_long_memory(self, path: Path) -> None:
        self.write_vocab(path)
