from __future__ import annotations

import pprint
import re
from pathlib import Path
from typing import Any

from rdkit import Chem


class FeatureAggregateAgent:
    """Aggregate discovered drug SMARTS and target fragments into a feature vocabulary."""

    def __init__(self, substructures: dict[str, Any] | None = None, fragments: dict[str, Any] | None = None) -> None:
        self.substructures: dict[str, dict[str, Any]] = dict(substructures or {})
        self.fragments: dict[str, dict[str, Any]] = dict(fragments or {})

    def _parse_numbered_items(self, text: str) -> list[str]:
        items: list[str] = []
        for line in text.splitlines():
            cleaned = line.strip()
            if not cleaned:
                continue
            cleaned = re.sub(r"^\s*(?:\d+[\).:-]\s*|-+\s*)", "", cleaned).strip()
            cleaned = cleaned.strip("`'\" ")
            if cleaned:
                items.append(cleaned)
        return items

    def add_drug_features(self, text: str) -> int:
        added = 0
        for smarts in self._parse_numbered_items(text):
            mol = Chem.MolFromSmarts(smarts)
            if mol is None:
                continue
            canonical = Chem.MolToSmarts(mol)
            if canonical in self.substructures:
                self.substructures[canonical]["count"] = self.substructures[canonical].get("count", 0) + 1
                if smarts not in self.substructures[canonical].setdefault("smile", []):
                    self.substructures[canonical]["smile"].append(smarts)
            else:
                self.substructures[canonical] = {"count": 1, "smile": [smarts]}
                added += 1
        return added

    def add_target_features(self, text: str) -> int:
        added = 0
        for fragment in self._parse_numbered_items(text):
            normalized = re.sub(r"[^A-Za-z]", "", fragment).upper()
            if not normalized:
                continue
            if normalized in self.fragments:
                self.fragments[normalized]["count"] = self.fragments[normalized].get("count", 0) + 1
            else:
                self.fragments[normalized] = {"count": 1}
                added += 1
        return added

    def write_vocab(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        body = [
            "# Generated by KnowMol FeatureAggregateAgent",
            "substructure_patterns = "
            + pprint.pformat(self.substructures, sort_dicts=False, width=120),
            "",
            "binding_fragments = " + pprint.pformat(self.fragments, sort_dicts=False, width=120),
            "",
        ]
        path.write_text("\n".join(body))
